/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.jsoft.jdesktop.kundenstamm.customersearch;

import de.jsoft.jdesktop.kundenstamm.Kundenstramm;
import de.jsoft.jdesktop.kundenstamm.MKundenstamm;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static org.springframework.shell.table.CellMatchers.table;

/**
 *
 * @author hoscho
 */
public class JIFrameCustomerSearch extends javax.swing.JInternalFrame  {

    
     String kdnummer;
     String searchuser;
     String searchstrasse;
     Integer searchplz;
     String searchort;
    
     DefaultTableModel model;

     de.jsoft.jdesktop.kundenstamm.Kundenstramm kdstamm;
     /*
      * Creates new form JIFrameCustomerSearch
      */
    public JIFrameCustomerSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Search Customer");

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:



        int rowcount = jTable1.getSelectedRow();
        de.jsoft.jdesktop.kundenstamm.Kundenstramm kdstamm = new de.jsoft.jdesktop.kundenstamm.Kundenstramm();

        String test = Kundenstramm.searchresult.get(rowcount).getKontoNr().toString();


        kdstamm.getjTextField13().getText();
        kdstamm.jTextField13.setText(Kundenstramm.searchresult.get(rowcount).getKontoNr().toString());
        kdstamm.getjTextField13().setText(Kundenstramm.searchresult.get(rowcount).getKontoNr().toString());

        kdstamm.repaint();
        this.dispose();

        
    }//GEN-LAST:event_jTable1MouseClicked


    public void addDatatoTable(List<MKundenstamm> searchresult)
    {
        model = new DefaultTableModel(
        
      new Object[][]
      {
          
          /*
            {  
                searchuser, searchstrasse, searchplz, searchort 
                
            }, 
*/
           
      },
      new Object[] { "KontoNummer", "Name", "Strasse", "PLZ", "Ort" });
        
        
         for(int i = 0; i < searchresult.size(); i++)
       {
              kdnummer = searchresult.get(i).getKundennummer();
              searchuser = searchresult.get(i).getKundenname();
              searchstrasse = searchresult.get(i).getStrasse();
              searchplz = searchresult.get(i).getPlz();
              searchort = searchresult.get(i).getOrt();
              
             
            
              //model.addRow(searchuser, searchstrasse, searchplz, searchort);
         
              model.addRow(new Object[]{ kdnummer, searchuser, searchstrasse, searchplz, searchort});
       }
        
     
   
      this.jTable1.setModel(model);
    }

    public DefaultTableModel getModel() {
        return model;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
